# Generated by Django 3.2.7 on 2021-09-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
