# Generated by Django 3.2.7 on 2021-09-27 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0002_auto_20210926_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
