# Generated by Django 3.2.7 on 2021-09-27 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0004_alter_images_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
