# Generated by Django 3.2.7 on 2021-09-27 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0005_alter_images_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
